apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-rhacm
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-gitops
  project: config
  source:
    repoURL: 'https://github.com/electron1162/rhacm.git'
    path: "netpol"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true